[project]
name = "story-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.136.1",
    "groq>=1.1.2",
    "pydantic-ai>=1.82.0",
    "python-dotenv>=1.2.2",
    "requests>=2.33.1",
    "uvicorn>=0.44.0",
]

[dependency-groups]
dev = [
    "git-filter-repo>=2.47.0",
    "jupyter>=1.1.1",
    "pandas>=3.0.2",
]
